### ISSUE TITLE
Dotenv install

### ISSUE THREAD

**Issue by tcarmet** [auth0-samples/auth0-python-web-app#16]
Hello

I had some issue when installing all the project dependencies from the `requirements.txt` file. It seems that the package `dotenv` is not properly named.

I had the following error when running the app.
```shell
Traceback (most recent call last):
  File "server.py", line 9, in <module>
    from dotenv import load_dotenv
ImportError: No module named dotenv
```

I was able to fix  this issue by doing the following :
```shell
pip uninstall dotenv # uninstalling dotenv to avoid conflicts
pip install python-dotenv # install the proper package
```

I recommend changing the name of the package from `dotenv` to `python-dotenv` if you guys are facing this issue as well.

have a nice day 😄

**Comment by chenkie** [comment]
thanks for the heads up!
