### ISSUE TITLE
Python 2.7 vs Python 3

### ISSUE THREAD

**Issue by edlee123** [auth0-samples/auth0-python-web-app#34]
Think it'll save people some headaches to indicate here, and in the python Quickstart which version of python the example is in.   

I first tried this in a virtualenv with python 3.5, and took me longer than I would have liked until I found this about jose dependency in python 3 :   
https://stackoverflow.com/questions/47390278/django-auth0-a-bytes-like-object-is-required-not-str-python-3-5-2

Works fine in python 2.7 though

**Comment by aaguiarz** [comment]
We just changed it to not to use jose, if you could give it another try and let us know if it works for you, it would be great.

Thanks!

**Comment by edlee123** [comment]
cheers will let you know
