### ISSUE TITLE
invalid_grant: redirect_uri is required if it was included in the authorization request.

### ISSUE THREAD

**Issue by rubyAce71697** [auth0-samples/auth0-python-web-app#53]
Auth0 Callback URL = http://localhost:3000/callback

Authorization redirect URL: https://dev-d67-1kl7.auth0.com/authorize?response_type=code&client_id=Aagx9t5baBdrZ3rIin4fMqfMw9Kq4V3E&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&scope=openid+profile&state=UQ6QAgMDQErF8mDE3eVwdY0T6FAwDQ&audience=https%3A%2F%2Fdev-d67-1kl7.auth0.com%2Fuserinfo

Access token post URL:
https://dev-d67-1kl7.auth0.com/oauth/token?grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback&code=Nu_01CVROeZk9gfj&state=UQ6QAgMDQErF8mDE3eVwdY0T6FAwDQ

Can someone please help on this issue.

**Comment by joshcanhelp** [comment]
@rubyAce71697 - Your token URL is a little odd. Is this something the sample generated for you? The application should just POST to `https://dev-d67-1kl7.auth0.com/oauth/token` (no parameters) with a body that includes the `code`, `grant_type`, `redirect_uri`, `client_id`, and `client_secret`. The SDK should doing that work for you, though. Are you building this URL yourself?
