### ISSUE TITLE
seed project bugs

### ISSUE THREAD

**Issue by zenyui** [auth0-samples/auth0-python-web-app#6]
Two bugs in the seed project:

- readme should specify that users must add the callback url to their client settings
- pre-filled seed project (on Auth0 client page) does find/replace on "{domain}" in the code, but this is already handled by the code `token_url = 'https://{domain}/oauth/token'.format(domain=env[constants.AUTH0_DOMAIN])`, etc.

**Comment by chenkie** [comment]
Fixed by #7
