### ISSUE TITLE
The 'session' cookie is too large

### ISSUE THREAD

**Issue by vpetersson** [auth0-samples/auth0-python-web-app#67]
I was toying around with this example over the weekend and more or less just cloned the demo code. I'm able to load the login page just fine, but when trying to log in, I get this:

```
 /usr/local/lib/python3.9/site-packages/werkzeug/sansio/response.py:230: UserWarning: The 'session' cookie is too large: the value was 5400 bytes but the header required 26 extra bytes. The final size was 5426 bytes but the limit is 4093 bytes. Browsers may silently ignore cookies larger than this.
```

The error is pretty self explanatory, and is triggered by [server.py#L46](https://github.com/auth0-samples/auth0-python-web-app/blob/master/01-Login/server.py#L46).

Adding a simple `print()` statement to `server.py`, I'm able to verify that the payload returned by `oauth.auth0.authorize_access_token()` is fine. 

I haven't tried rolling back the versions yet, but I'm using the latest versions of all dependencies:

```
Flask==2.2.2
Authlib==1.2.0
requests==2.28.2
```

**Update:** Rolling back to pinned versions in [requirements.txt](https://github.com/auth0-samples/auth0-python-web-app/blob/master/01-Login/requirements.txt) doesn't make a difference.

**Comment by vpetersson** [comment]
I've worked around the issue by doing `token['userinfo']['picture'] = ''`, which cuts down the size a tad, but isn't a great workaround.

**Comment by shemar100** [comment]
Going to try to find look into a solution for this.

**Comment by adamjmcgrath** [comment]
Hi @vpetersson - thanks for raising this

I've just tested this and the token payload was 2,412 bytes - so I think in most cases this should fit on a cookie.

For cases like yours when it's larger than 4,096 bytes - you might want to make a decision about what you want to store, or use a different storage mechanism, but these decisions are out of scope of a simple sample application.
